### ISSUE TITLE
Why convert MPII into single person patches

### ISSUE THREAD

**Issue by cailile** [meghshukla/ActiveLearningForHumanPose#3]
Hi Megh,

I noticed that in the class of HumanPoseDataLoader, mpii_single_person_extractor() is called to convert images with multiple persons into multiple image-gt pairs so that each pair only has 1 person's pose as ground truth. I am wondering why this step is necessary? Is it due to the limitation of the pose estimation network or the limitation of AL algorithm? 

I am wondering whether  it makes more sense to remove mpii_single_person_extractor() when constructing the training and val splits --  in practice, you cannot do this form of conversion without ground truth labelling, rendering the current setting unrealistic. Any comments? Thanks!

**Comment by meghshukla** [comment]
Hello,
Thank you for the question.
In practice most active learning algorithms for human pose estimation are compatible with top-down methods. Top-down methods first detect the person using object detection and then using the crop around this person they perform pose estimation.

Therefore in practice [1] we assume that the top-down human pose estimator identifies different instances of humans, takes a crop around them, and then performs pose estimation. We simplify this by directly taking the crop around the person, since our goal is to show that some active learning algorithms are better able to identify pose ambiguities than others.

As you rightly said, our approach is not compatible with bottom-up multi-person pose estimation and can be used only for top-down multi-person pose estimation in the current setting.

Please let me known if you need any further clarifications!

Best,
Megh

[1] Deep High-Resolution Representation Learning for Human Pose Estimation, CVPR 2019

**Comment by cailile** [comment]
Hi Megh,

Thanks for the detailed explanation. The current setting with mpii_single_person_extractor() is reasonable assuming that a high-performance human detector is able to generate reliable bounding boxes for the following pose estimation step, which should not be a problem for modern human detectors.
